DELETE http://localhost:3001/api/blogs/5f8c97f2cfe6781a7c5ca970
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikxvc2VyMyIsImlkIjoiNWY4Yzc0ZDJjNjJkYmE0MmQ0MjA3NmY0IiwiaWF0IjoxNjAzMDQ3Nzg2fQ.WwY9KBNkhpd4NrBNzDx6pYiBFNY0o6tAUIiHkdS8_c0
